# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/rosemary/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),rosemary)
$(call add-radio-file-sha1-checked,radio/scp.img,e4778bed556c485bb1fecdaa807acf8cd15cc362)
$(call add-radio-file-sha1-checked,radio/gz.img,541ff810d11933579faa99b89f327bf5be29d7aa)
$(call add-radio-file-sha1-checked,radio/lk.img,4d71b4cebf598b69141ca91b7e7e72b02b099b66)
$(call add-radio-file-sha1-checked,radio/cust.img,64df8a3203fc5b81ba6737393cb4238bcaf136f0)
$(call add-radio-file-sha1-checked,radio/cam_vpu3.img,d624623dec76cedea4ef7de043cc6be4671bb437)
$(call add-radio-file-sha1-checked,radio/audio_dsp.img,183739c693eaf353c6d2112bd74acfb5e1c9ce57)
$(call add-radio-file-sha1-checked,radio/cam_vpu1.img,8e4de3630c838b95fa90609ec74fbdb48f621b09)
$(call add-radio-file-sha1-checked,radio/sspm.img,9324c38baa35eeb1044f50464034a225d334af50)
$(call add-radio-file-sha1-checked,radio/md1img.img,e9e763c2e3f0330926e0357f32836cff88bda31a)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,eccf40a4144e8254277baeb0a836f27f2b6e9c4e)
$(call add-radio-file-sha1-checked,radio/cam_vpu2.img,9fb1448b4a688abcd294c6c4d90f51891fa763f4)
$(call add-radio-file-sha1-checked,radio/tee.img,f44739a694224ad94d3841e945f1c1d48b36c735)
$(call add-radio-file-sha1-checked,radio/spmfw.img,c26415955d6a26906ca32e39972b406410cd4141)
$(call add-radio-file-sha1-checked,radio/logo.bin,3fec065c0f35853692bcea9661902939876fa694)
endif
